### ISSUE TITLE
i have a problems with addon (i will send a screenshot)

### ISSUE THREAD

**Issue by Agent312** [grande1900/csw#1]
![Screenshot_40](https://user-images.githubusercontent.com/111993882/186441148-d8a326d3-b961-459f-bfe8-8f6654faee45.png)

**Comment by grande1900** [comment]
Is the issue still persisting?
Also, are you using the workshop or github version?

**Comment by Agent312** [comment]
workshop version

**Comment by Agent312** [comment]
i think it's fixed

**Comment by grande1900** [comment]
> i think it's fixed

Yeah, I think that's just caused when using the addon for the first time. I'll add a check to make sure the table isn't nil.
